=== denkbares/d3web/d3web/d3web-Dialog2/src/main/resources/de/d3web/dialog2/dialoglayout.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="QContainers">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Default" type="Default" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="QContainer" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:choice minOccurs="0" maxOccurs="unbounded">
							<xsd:element name="Dimension" type="Dimension"
								minOccurs="1" maxOccurs="1" />
							<xsd:element name="Default" type="Default" minOccurs="0"
								maxOccurs="1" />
							<xsd:element name="Question" type="Question" />
							<xsd:element name="HtmlText">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Position" type="Position"
											minOccurs="1" maxOccurs="1" />
										<xsd:element name="HtmlTextContent" type="xsd:string"
											minOccurs="1" maxOccurs="1" />
									</xsd:sequence>
									<xsd:attribute name="questionBinding" type="xsd:string" />
									<xsd:attribute name="additionalCSSStyle" type="xsd:string" />
									<xsd:attribute name="additionalCSSClass" type="xsd:string" />
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
						<xsd:attribute name="id" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Dimension">
		<xsd:attribute name="rows" type="xsd:integer" use="required" />
		<xsd:attribute name="cols" type="xsd:integer" use="required" />
	</xsd:complexType>
	<xsd:complexType name="Default">
		<xsd:sequence>
			<xsd:element name="QContainerHeadline" type="QContainerHeadline"
				minOccurs="0" maxOccurs="1" />
			<xsd:element name="QuestionHeadline" type="QuestionHeadline"
				minOccurs="0" maxOccurs="1" />
			<xsd:element name="QuestionAnswers" type="QuestionAnswers"
				minOccurs="0" maxOccurs="1" />
			<xsd:element name="ImageMap" type="ImageMap" minOccurs="0"
				maxOccurs="1" />
			<xsd:element name="MMInfo" type="MMInfo" minOccurs="0"
				maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="gridgap" type="xsd:integer"
			default="0" />
		<xsd:attribute name="padding" type="xsd:string" default="2px" />
		<xsd:attribute name="qContainerBorder" type="xsd:string"
			default="1px solid #000" />
		<xsd:attribute name="questionBorder" type="xsd:string"
			default="1px solid #000" />
		<xsd:attribute name="questionVerticalAlign" type="xsd:string"
			default="top" />
		<xsd:attribute name="additionalCSSStyle" type="xsd:string" />
		<xsd:attribute name="additionalCSSClass" type="xsd:string" />
		<xsd:attribute name="currentQuestionBackground" type="xsd:string"
			default="#FFFFCC" />
		<xsd:attribute name="answeredQuestionBackground" type="xsd:string"
			default="#F0F0F0" />
		<xsd:attribute name="unansweredQuestionBackground" type="xsd:string"
			default="#DFFDDF" />
		<xsd:attribute name="questionColumns" type="xsd:integer"
			default="2" />
	</xsd:complexType>
	<xsd:complexType name="Question">
		<xsd:sequence>
			<xsd:element name="Position" type="Position" minOccurs="1"
				maxOccurs="1" />
			<xsd:element name="QuestionHeadline" type="QuestionHeadline"
				minOccurs="0" maxOccurs="1" />
			<xsd:element name="QuestionAnswers" type="QuestionAnswers"
				minOccurs="0" maxOccurs="1" />
			<xsd:element name="MMInfo" type="MMInfo" minOccurs="0"
				maxOccurs="1" />
			<xsd:element name="QuestionImage" type="QuestionImage"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="padding" type="xsd:string" default="2px" />
		<xsd:attribute name="border" type="xsd:string" default="1px solid #000" />
		<xsd:attribute name="verticalAlign" type="xsd:string"
			default="top" />
		<xsd:attribute name="additionalCSSStyle" type="xsd:string" />
		<xsd:attribute name="additionalCSSClass" type="xsd:string" />
		<xsd:attribute name="currentQuestionBackground" type="xsd:string"
			default="#FFFFCC" />
		<xsd:attribute name="answeredQuestionBackground" type="xsd:string"
			default="#F0F0F0" />
		<xsd:attribute name="unansweredQuestionBackground" type="xsd:string"
			default="#DFFDDF" />
	</xsd:complexType>
	<xsd:complexType name="Position">
		<xsd:attribute name="posX" type="xsd:string" use="required" />
		<xsd:attribute name="posY" type="xsd:string" use="required" />
	</xsd:complexType>
	<xsd:complexType name="QContainerHeadline">
		<xsd:attribute name="showHeadline" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="altText" type="xsd:string" />
		<xsd:attribute name="border" type="xsd:string" default="1px solid #000" />
		<xsd:attribute name="background" type="xsd:string"
			default="#eee" />
		<xsd:attribute name="color" type="xsd:string" default="#000" />
		<xsd:attribute name="font" type="xsd:string" />
		<xsd:attribute name="padding" type="xsd:string" default="5px" />
	</xsd:complexType>
	<xsd:complexType name="QuestionHeadline">
		<xsd:attribute name="showHeadline" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="showButton" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="border" type="xsd:string" />
		<xsd:attribute name="background" type="xsd:string"
			default="#eee" />
		<xsd:attribute name="color" type="xsd:string" default="#000" />
		<xsd:attribute name="font" type="xsd:string" />
		<xsd:attribute name="margin" type="xsd:string" default="0px 0px 5px 0px" />
	</xsd:complexType>
	<xsd:complexType name="QuestionAnswers">
		<xsd:attribute name="answerChoiceType" type="answerChoiceType"
			default="checkbox" />
		<xsd:attribute name="color" type="xsd:string" default="#000" />
		<xsd:attribute name="font" type="xsd:string" />
		<xsd:attribute name="columns" type="xsd:integer"
			default="0" />
		<xsd:attribute name="inputWidth" type="xsd:string"
			default="200px" />
		<xsd:attribute name="inputHeight" type="xsd:string"
			default="100px" />
		<xsd:attribute name="fastAnswer" type="xsd:boolean"
			default="false" />
		<xsd:attribute name="qTextDisplayMode" type="QTextDisplayModeType"
			default="textarea" />
		<xsd:attribute name="margin" type="xsd:string" default="0px 5px" />
	</xsd:complexType>
	<xsd:complexType name="ImageMap">
		<xsd:attribute name="headlineText" type="xsd:string" />
		<xsd:attribute name="showRegionOnMouseOver" type="xsd:boolean"
			default="true" />
	</xsd:complexType>
	<xsd:complexType name="MMInfo">
		<xsd:attribute name="align" type="alignmentType"
			default="left" />
		<xsd:attribute name="position" type="InfoPositionType"
			default="headline" />
		<xsd:attribute name="mouseEvent" type="MouseEventType"
			default="onclick" />
		<xsd:attribute name="padding" type="xsd:string" default="2px" />
		<xsd:attribute name="tooltipWidth" type="xsd:integer"
			default="0" />
	</xsd:complexType>
	<xsd:complexType name="QuestionImage">
		<xsd:sequence>
			<xsd:element name="AnswerRegion" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="answerID" type="xsd:string" use="required" />
					<xsd:attribute name="xStart" type="xsd:integer" use="required" />
					<xsd:attribute name="xEnd" type="xsd:integer" use="required" />
					<xsd:attribute name="yStart" type="xsd:integer" use="required" />
					<xsd:attribute name="yEnd" type="xsd:integer" use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="file" type="xsd:string" use="required" />
		<xsd:attribute name="align" type="alignmentType"
			default="center" />
		<xsd:attribute name="answersPosition" type="AnswersPositionType"
			default="hidden" />
		<xsd:attribute name="showRegionOnMouseOver" type="xsd:boolean"
			default="true" />
	</xsd:complexType>
	<xsd:simpleType name="answerChoiceType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="dropdown" />
			<xsd:enumeration value="list" />
			<xsd:enumeration value="checkbox" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="alignmentType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="left" />
			<xsd:enumeration value="center" />
			<xsd:enumeration value="right" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="InfoPositionType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="top" />
			<xsd:enumeration value="bottom" />
			<xsd:enumeration value="headline" />
			<xsd:enumeration value="hidden" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AnswersPositionType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="top" />
			<xsd:enumeration value="bottom" />
			<xsd:enumeration value="left" />
			<xsd:enumeration value="right" />
			<xsd:enumeration value="hidden" />
			<xsd:enumeration value="none" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MouseEventType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="onclick" />
			<xsd:enumeration value="onmouseover" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="QTextDisplayModeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="textarea" />
			<xsd:enumeration value="textfield" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== denkbares/d3web/d3web/d3web-Dialog2/src/main/webapp/kbResources/kfz2K/multimedia/dialoglayout.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<QContainers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../WEB-INF/classes/de/d3web/dialog2/dialoglayout.xsd">
	<!--
		<Default gridgap="0" padding="1px" qContainerBorder="1px solid black"
		questionBorder="1px solid black"> </Default>
	-->
	<!--
		<Default gridgap="3" padding="3px" qContainerBorder=""
		questionBorder="1px dotted red"> <QuestionHeadline showHeadline="true"
		showButton="true" color="#222" headlineMargin="0px 0px 15px 10px" />
		<QuestionAnswers answerChoiceType="checkbox" columns="1" color="#444"
		font="" inputWidth="" inputHeight="" /> </Default>
	-->
	<!-- Allgemeines -->
	<QContainer id="Q56">
		<Dimension rows="2" cols="1" />
		<Default gridgap="1" padding="" qContainerBorder=""
			questionBorder="3px outset #00f">
			<QuestionHeadline showHeadline="true" showButton="true"
				color="#fff" />
			<QuestionAnswers answerChoiceType="checkbox" columns="0"
				color="#f00" />
		</Default>
		<Question id="Mf58" padding="" border=""> <!-- Baujahr -->
			<Position posX="0" posY="0" />
			<QuestionHeadline showHeadline="true" showButton="true"
				color="" />
			<QuestionAnswers columns="0" />
		</Question>
		<Question id="Mf57"> <!-- Automarke -->
			<Position posX="0" posY="1" />
			<QuestionHeadline showHeadline="false" showButton="true"
				color="#0ff" />
			<QuestionAnswers answerChoiceType="checkbox" columns="5"
				color="#00f" font="" inputWidth="" inputHeight="" />
		</Question>
	</QContainer>
    
    <!-- Detailangaben -->
	<QContainer id="Q66">
		<Dimension rows="1" cols="1" />
		<Default gridgap="1" padding="15px 10px">
			<QuestionHeadline showHeadline="true" showButton="true"
				color="" />
			<QuestionAnswers answerChoiceType="checkbox" columns="0"
				color="" font="" inputWidth="" inputHeight="" />
		</Default>
		<Question id="Mf54" padding="5px" border="3px dotted green">
			<!--
				Autotyp
			-->
			<Position posX="0" posY="0" />
			<QuestionHeadline showHeadline="false" showButton="true"
				color="" />
			<QuestionAnswers answerChoiceType="list" columns="4"
				color="" font="" inputWidth="180px" inputHeight="130px" />
		</Question>
	</QContainer>
    
    
    
    <!-- Beobachtungen -->
	<QContainer id="Q16">
		<Dimension rows="5" cols="3" />
		<!--
			<Default gridgap="10" padding="15px" questionBorder="1px solid #0f0">
			<QuestionHeadline showHeadline="true" showButton="true" />
			<QuestionAnswers answerChoiceType="checkbox" /> </Default>
		-->
		<Question id="Mf2"><!-- Abgase -->
			<Position posX="0" posY="0" />
		</Question>
		<Question id="Mf8"><!-- Verhalten Motorstart -->
			<Position posX="1-2" posY="0" />
		</Question>
		<!--
			<HtmlText> <Position posX="0-2" posY="1"/> <HtmlTextContent>
			<![CDATA[ <h2>huhu, ich bin eine Box hier drinne!</h2> <p>Ein Bild
			aus dem MM Ordner mit width 100px: <Image
			width="100px">dorfongolf.jpg</Image></p> ]]> </HtmlTextContent>
			</HtmlText>
		-->
		<Question id="Mf3"><!-- Auspuffrohrfarbe -->
			<Position posX="0-2" posY="1" />
			<QuestionImage file="auspuff_pic_temp.jpg" align="center"
				answersPosition="right">
				<AnswerRegion answerID="Mf3a1" xStart="0" xEnd="219"
					yStart="0" yEnd="138" />
				<AnswerRegion answerID="Mf3a3" xStart="221" xEnd="479"
					yStart="0" yEnd="138" />
				<AnswerRegion answerID="Mf3a2" xStart="0" xEnd="219"
					yStart="140" yEnd="307" />
				<AnswerRegion answerID="Mf3a4" xStart="221" xEnd="479"
					yStart="140" yEnd="307" />
			</QuestionImage>
		</Question>
		<Question id="Mf4"><!-- Bezinart -->
			<Position posX="0" posY="2-3" />
		</Question>
		<Question id="Mf5"> <!-- Ueblicher Verbrauch -->
			<Position posX="1-2" posY="2" />
		</Question>
		<Question id="Mf6"><!-- Tatsaechl. Verbrauch -->
			<Position posX="1-2" posY="3" />
		</Question>
		<Question id="Mf7"><!-- Motorgeraeusche -->
			<Position posX="0" posY="4" />
		</Question>
		<Question id="Mf9"><!-- Fahrverhalten -->
			<Position posX="1-2" posY="4" />
		</Question>
		<!--
			<HtmlText> <Position posX="2" posY="4-5" /> <HtmlTextContent>
			<![CDATA[<h3 style="color: red">oh, hier is ja noch eine!</h3>]]>
			</HtmlTextContent> </HtmlText>
		-->
	</QContainer>
</QContainers>
