=== denkbares/d3web/d3web/d3web-Dialog2/src/main/java/de/d3web/dialog2/dialogsettings.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="DialogSettings">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Dialog" type="Dialog" minOccurs="1"
					maxOccurs="1" />
				<xsd:element name="QuestionPage" type="QuestionPage"
					minOccurs="1" maxOccurs="1" />
				<xsd:element name="Diagnoses" type="Diagnoses"
					minOccurs="1" maxOccurs="1" />
				<xsd:element name="Explanation" type="Explanation"
					minOccurs="1" maxOccurs="1" />
				<xsd:element name="MMInfo" type="MMInfo" minOccurs="1"
					maxOccurs="1" />
				<xsd:element name="CompareCase" type="CompareCase"
					minOccurs="1" maxOccurs="1" />
				<xsd:element name="XCL" type="XCL" minOccurs="1"
					maxOccurs="1" />
				<xsd:element name="ProcessedQContainers" type="ProcessedQContainers"
					minOccurs="1" maxOccurs="1" />
				<xsd:element name="Frequentness" type="Frequentness"
					minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Dialog">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="leftPanelSizePercent" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:double"
						default="20.0" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="rightPanelSizePercent" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:double"
						default="20.0" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="leftPanelFixed" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="allowRightPanel" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showRightPanelToggleButtons"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="saveCaseThreadMaxIdleTime" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:long" default="0" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="sessionMaxInactiveInterval" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:long" default="7200" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showManagementButton" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showDialogButton" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="timeZone" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"
						default="Europe/Berlin" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showCountryFlags" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showPageHeader" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showPageFooter" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="QuestionPage">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="autoMoveToResultpage" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showQuestionPageAnswerButton"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showQuestionPageResultButton"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showQuestionPageUnknownButton"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="questionMinAnsWrap" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:integer"
						default="6" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="questionDateDefaultDatesection"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="Datesection"
						default="full" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="dialogMode" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="DialogMode"
						default="MQ" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="mCConstraintsAutoGrayOut" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showQASetTreeTab" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showDiagnosesTreeTab" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showAbstractQuestions" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Diagnoses">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="showHeuristicDiagnoses" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showHeuristicEstablishedDiagnoses"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showHeuristicSuggestedDiagnoses"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showHeuristicExcludedDiagnoses"
				minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Explanation">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="showDiagExplanation" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showDiagReason" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showDiagConcreteDerivation" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showDiagDerivation" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MMInfo">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="showMMInfo" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="maxCharLengthInMMInfoPopup" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:integer"
						default="50" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CompareCase">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="showCompareCase" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="XCL">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="showXCL" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="displayMinPercentage" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:double"
						default="0.15" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="digitcount" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:integer"
						default="2" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ProcessedQContainers">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="showProcessedQContainers" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showAll" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="false" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="maxInput" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:integer"
						default="8" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showUnknown" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="false" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="qTextMode" minOccurs="1" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="QTextMode" default="text" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showQContainerNames" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showUnknownIcon" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="showQContainerNamesIcon" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Frequentness">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="showFrequentness" minOccurs="1"
				maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:boolean"
						default="true" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="Datesection">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="full" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="time" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DialogMode">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="MQ" />
			<xsd:enumeration value="OQ" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="QTextMode">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="text" />
			<xsd:enumeration value="prompt" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== denkbares/d3web/d3web/d3web-Dialog2/src/main/webapp/kbResources/test_kfz_extended/multimedia/dialogsettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<DialogSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dialogsettings.xsd">
	<Dialog>
		<leftPanelSizePercent value="20.0" />
		<rightPanelSizePercent value="20.0" />
		<allowRightPanel value="true" />
		<showRightPanelToggleButtons value="true" />
		<saveCaseThreadMaxIdleTime value="0" />
		<!--
			time in milliseconds when the savecasethread will be executed. '0'
			for no saveCaseThread
		-->
		<sessionMaxInactiveInterval value="7200" /> <!-- time in seconds when the HTTP session will expire -->
		<showManagementButton value="true" />
		<showDialogButton value="true" />
		<timeZone value="Europe/Berlin" />
		<showCountryFlags value="true" />
		<showPageHeader value="true" />
		<showPageFooter value="true" />
	</Dialog>
	<QuestionPage>
		<autoMoveToResultpage value="true" /> <!-- move to result page if all containers are answered by the user -->
		<showQuestionPageAnswerButton value="true" />
		<showQuestionPageResultButton value="true" />
		<showQuestionPageUnknownButton value="true" />
		<questionMinAnsWrap value="6" />
		<questionDateDefaultDatesection value="full" />
		<!--
			possible options: 'date', 'time', 'full'
		-->
		<dialogMode value="MQ" />
		<!--
			possible options: 'MQ', 'OQ'
		-->
		<mCConstraintsAutoGrayOut value="true" />
		<showQASetTreeTab value="true" />
		<showDiagnosesTreeTab value="true" />
	</QuestionPage>
	<Diagnoses>
		<showHeuristicDiagnoses value="true" />
		<showHeuristicEstablishedDiagnoses
			value="true" />
		<showHeuristicSuggestedDiagnoses
			value="true" />
		<showHeuristicExcludedDiagnoses value="true" />
	</Diagnoses>
	<Explanation>
		<showDiagExplanation value="true" />
		<showDiagReason value="true" />
		<showDiagConcreteDerivation value="true" />
		<showDiagDerivation value="true" />
	</Explanation>
	<MMInfo>
		<showMMInfo value="true" />
		<maxCharLengthInMMInfoPopup value="50" />
	</MMInfo>
	<CompareCase>
		<showCompareCase value="true" />
	</CompareCase>
	<XCL>
		<showXCL value="true" />
		<displayMinPercentage value="0.15" />
		<digitcount value="2" />
	</XCL>
	<ProcessedQContainers>
		<showProcessedQContainers value="true" />
		<showAll value="false" />
		<maxInput value="8" />
		<showUnknown value="false" />
		<qTextMode value="text" />
		<!--
			possible options: 'prompt', 'text'
		-->
		<showQContainerNames value="true" />
		<showUnknownIcon value="true" />
		<showQContainerNamesIcon value="true" />
	</ProcessedQContainers>
</DialogSettings>

=== denkbares/d3web/d3web/d3web-Dialog2/src/main/webapp/kbResources/rheumacheck_b2/multimedia/dialogsettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<DialogSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dialogsettings.xsd">
	<Dialog>
		<leftPanelSizePercent value="5.0" />
		<rightPanelSizePercent value="5.0" />
		<allowRightPanel value="false" />
		<showProgressBar value="true" />
		<showRightPanelToggleButtons value="false" />
		<saveCaseThreadMaxIdleTime value="0" />
		<!--
			time in milliseconds when the savecasethread will be executed. '0'
			for no saveCaseThread
		-->
		<sessionMaxInactiveInterval value="7200" /> <!-- time in seconds when the HTTP session will expire -->
		<showManagementButton value="false" />
		<showDialogButton value="false" />
		<timeZone value="Europe/Berlin" />
		<showCountryFlags value="false" />
		<showPageHeader value="false" />
		<showPageFooter value="false" />
	</Dialog>
	<QuestionPage>
		<autoMoveToResultpage value="true" /> <!-- move to result page if all containers are answered by the user -->
		<showQuestionPageAnswerButton value="true" />
		<showQuestionPageResultButton value="false" />
		<showQuestionPageUnknownButton value="false" />
		<questionMinAnsWrap value="6" />
		<questionDateDefaultDatesection value="full" />
		<!--
			possible options: 'date', 'time', 'full'
		-->
		<dialogMode value="MQ" />
		<!--
			possible options: 'MQ', 'OQ'
		-->
		<mCConstraintsAutoGrayOut value="true" />
		<showQASetTreeTab value="false" />
		<showDiagnosesTreeTab value="false" />
	</QuestionPage>
	<Diagnoses>
		<showHeuristicDiagnoses value="true" />
		<showHeuristicEstablishedDiagnoses
			value="true" />
		<showHeuristicSuggestedDiagnoses
			value="true" />
		<showHeuristicExcludedDiagnoses value="true" />
	</Diagnoses>
	<Explanation>
		<showDiagExplanation value="true" />
		<showDiagReason value="true" />
		<showDiagConcreteDerivation value="true" />
		<showDiagDerivation value="true" />
	</Explanation>
	<MMInfo>
		<showMMInfo value="true" />
		<maxCharLengthInMMInfoPopup value="50" />
	</MMInfo>
	<CompareCase>
		<showCompareCase value="true" />
	</CompareCase>
	<SCM>
		<showSCM value="true" />
		<displayMinPercentage value="0.15" />
		<digitcount value="2" />
	</SCM>
	<ProcessedQContainers>
		<showProcessedQContainers value="true" />
		<showAll value="false" />
		<maxInput value="8" />
		<showUnknown value="false" />
		<qTextMode value="text" />
		<!--
			possible options: 'prompt', 'text'
		-->
		<showQContainerNames value="true" />
		<showUnknownIcon value="true" />
		<showQContainerNamesIcon value="true" />
	</ProcessedQContainers>
	<Frequentness>
		<showFrequentness value="true" />
	</Frequentness>
</DialogSettings>
